name: GHA WorkFlow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.3'

        # - name: Set up Docker
        #   run: |
        #     mkdir -p ~/.docker
        #     for img in `ls ~/.docker`; do docker load -i ~/.docker/$img; done

    - name: TEST
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        exec sudo su -l $USER

    - name: Compile and test
      run: |
        sudo apt install build-essential

        git clone https://github.com/ethereum/hive
        cd ./hive
        go build .
        cd ..

        docker build --tag op-geth .

        # ./hive/hive --client=op-geth --sim=devp2p

        cd hive
        ./hive --sim devp2p --sim.limit discv4 --client go-ethereum,openethereum

        # cp -r ~/.go_workspace/src/github.com/karalabe/hive/workspace/logs/* $HOME/workflow/artifacts

    - name: Publish workflow artifacts
      uses: actions/upload-artifact@v2
      with:
        name: workflow-artifacts
        path: ${{ github.workspace }}/workflow/artifacts/
